- build: 0.28.1/centos/7
  image:
    - mesoscloud/mesos-slave:0.28.1-centos-7
    - mesoscloud/mesos-slave:0.28.1-centos
    - mesoscloud/mesos-slave:0.28.1
    - mesoscloud/mesos-slave:latest

- build: 0.28.1/ubuntu/14.04
  image:
    - mesoscloud/mesos-slave:0.28.1-ubuntu-14.04
    - mesoscloud/mesos-slave:0.28.1-ubuntu

- build: 0.28.0/centos/7
  image:
    - mesoscloud/mesos-slave:0.28.0-centos-7
    - mesoscloud/mesos-slave:0.28.0-centos
    - mesoscloud/mesos-slave:0.28.0

- build: 0.28.0/ubuntu/14.04
  image:
    - mesoscloud/mesos-slave:0.28.0-ubuntu-14.04
    - mesoscloud/mesos-slave:0.28.0-ubuntu

- build: 0.24.2/centos/7
  image:
    - mesoscloud/mesos-slave:0.24.2-centos-7
    - mesoscloud/mesos-slave:0.24.2-centos
    - mesoscloud/mesos-slave:0.24.2

- build: 0.24.2/ubuntu/14.04
  image:
    - mesoscloud/mesos-slave:0.24.2-ubuntu-14.04
    - mesoscloud/mesos-slave:0.24.2-ubuntu

- build: 0.24.1/centos/7
  image:
    - mesoscloud/mesos-slave:0.24.1-centos-7
    - mesoscloud/mesos-slave:0.24.1-centos
    - mesoscloud/mesos-slave:0.24.1

- build: 0.24.1/ubuntu/14.04
  image:
    - mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
    - mesoscloud/mesos-slave:0.24.1-ubuntu


- tests:
    - cmd: mesos-slave --version

    - cmd: test -z "$MESOS_CREDENTIAL"

    - cmd: test -n "$MESOS_CREDENTIAL"
      env:
        - SECRET=password

    - cmd: test -x /usr/bin/docker
