#!/bin/bash

HOST_IP="$(ip addr | grep inet | grep -v inet6 | grep -v '127.' | grep -v '172.' | head -n 1 | awk '{print $2}' | awk -F'/' '{print $1}')"
HOSTNAME="$(hostname)"

docker run -d \
    -e MYID=1 \
    -e SERVERS=${HOSTNAME} \
    --name=zookeeper --net=host --restart=always mesoscloud/zookeeper

sleep 15

docker run -d \
    -e MESOS_HOSTNAME=${HOSTNAME} \
    -e MESOS_IP=${HOST_IP} \
    -e MESOS_QUORUM=2 \
    -e MESOS_ZK=zk://${HOSTNAME}:2181/mesos \
    --name mesos-master --net host --restart always mesoscloud/mesos-master

sleep 15

docker run -d \
    -e MARATHON_HOSTNAME=${HOST_IP} \
    -e MARATHON_HTTPS_ADDRESS=${HOST_IP} \
    -e MARATHON_HTTP_ADDRESS=${HOST_IP} \
    -e MARATHON_MASTER=zk://${HOSTNAME}:2181/mesos \
    -e MARATHON_ZK=zk://${HOSTNAME}:2181/marathon \
    --name marathon --net host --restart always mesoscloud/marathon

sleep 15

docker run -d \
    -e MESOS_HOSTNAME=${HOSTNAME} \
    -e MESOS_IP=${HOST_IP} \
    -e MESOS_MASTER=zk://${HOSTNAME}:2181/mesos \
    -v /sys/fs/cgroup:/sys/fs/cgroup \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --name slave --net host --privileged --restart always \
    mesoscloud/mesos-slave


